apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: umbra-nexus-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "umbra-nexus-ip"
    networking.gke.io/managed-certificates: "umbra-nexus-ssl"
    kubernetes.io/ingress.class: "gce"
    # Redirect HTTP to HTTPS
    ingress.gcp.kubernetes.io/pre-shared-cert: "umbra-nexus-ssl"
spec:
  defaultBackend:
    service:
      name: umbra-nexus-service
      port:
        number: 80
